<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HJ68RE7" failures="1" tests="3" name="Test" time="10.01" errors="0" timestamp="2025-04-08T20:16:40 IST">
  <testcase classname="testng_programs.ListenersDemo" name="testlogo" time="0.073"/>
  <testcase classname="testng_programs.ListenersDemo" name="testurl" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/logi] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at testng_programs.ListenersDemo.testurl(ListenersDemo.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testurl -->
  <testcase classname="testng_programs.ListenersDemo" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- Test -->
